### ISSUE TITLE
'direnv current' results in 'panic: runtime error: index out of range'

### ISSUE THREAD

**Issue by gretel** [direnv/direnv#216]
```
$ direnv version
2.8.1
$ direnv current
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x41ab9e0, 0xc820012080)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
main.currentCommandFn(0xc82007a3c0, 0xc8200764a0, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/direnv20160411-24700-sr3woj/direnv-2.8.1/cmd_current.go:12 +0x1ca
main.CommandsDispatch(0xc82007a3c0, 0xc820088060, 0x2, 0x2, 0x0, 0x0)
	/private/tmp/direnv20160411-24700-sr3woj/direnv-2.8.1/commands.go:90 +0x3d3
main.main()
	/private/tmp/direnv20160411-24700-sr3woj/direnv-2.8.1/main.go:13 +0x98
```
i suggest adding a error message to suggest calling with a filename.

**Comment by zimbatm** [comment]
Thanks !
