### ISSUE TITLE
Occasional segfault on Mac

### ISSUE THREAD

**Issue by ide** [direnv/direnv#239]
I'm using direnv 2.9.0 with Bash 3.2.57(1) on macOS 10.12.1. Sometimes (not often) direnv will crash:

```
/bin/bash: line 1:  4857 Segmentation fault: 11  "/usr/local/Cellar/direnv/2.9.0/bin/direnv" dump
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x402745b]

runtime stack:
runtime.throw(0x42215e0, 0x2a)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x42e3140)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x42e3140, 0x80, 0x100000000, 0x404f516)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbff440)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x42e3140, 0x80, 0x10100000000, 0xc820016000)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0x100000, 0xc800000001, 0x4066b40)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0x42dfa00)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:245 fp=0xc82004b4e0 sp=0xc82004b4d8
runtime.mallocgc(0x100000, 0x4165140, 0x1, 0xc82000b5c0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:665 +0x9eb fp=0xc82004b5b8 sp=0xc82004b4e0
runtime.newarray(0x4165140, 0x20000, 0xc82000b5c0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:798 +0xc9 fp=0xc82004b5f8 sp=0xc82004b5b8
runtime.makeslice(0x415c1e0, 0x20000, 0x20000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/slice.go:32 +0x165 fp=0xc82004b648 sp=0xc82004b5f8
compress/flate.(*compressor).init(0xc82007cfc0, 0x4614470, 0xc82000fba0, 0x6, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/compress/flate/deflate.go:410 +0x849 fp=0xc82004b7e0 sp=0xc82004b648
compress/flate.NewWriter(0x4614470, 0xc82000fba0, 0xffffffffffffffff, 0xc820060480, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/compress/flate/deflate.go:487 +0x64 fp=0xc82004b820 sp=0xc82004b7e0
compress/flate.NewWriterDict(0x4614448, 0xc82005f1f0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/compress/flate/deflate.go:501 +0xbb fp=0xc82004b8d0 sp=0xc82004b820
compress/zlib.(*Writer).writeHeader(0xc820060480, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/compress/zlib/writer.go:134 +0x2b5 fp=0xc82004b980 sp=0xc82004b8d0
compress/zlib.(*Writer).Write(0xc820060480, 0xc8200ae0d4, 0x32, 0x40, 0x40, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/compress/zlib/writer.go:148 +0x42 fp=0xc82004b9e0 sp=0xc82004b980
main.marshal(0x41c0b00, 0xc820010ab0, 0x0, 0x0)
	/private/tmp/direnv-20160719-50748-1z0z1c4/direnv-2.9.0/marshal.go:22 +0x2e4 fp=0xc82004bb00 sp=0xc82004b9e0
main.(*EnvDiff).Serialize(0xc820010ab0, 0x0, 0x0)
	/private/tmp/direnv-20160719-50748-1z0z1c4/direnv-2.9.0/env_diff.go:113 +0x43 fp=0xc82004bb38 sp=0xc82004bb00
main.(*RC).RecordState(0xc82000ab10, 0xc82000abd0, 0xc82000b3b0)
	/private/tmp/direnv-20160719-50748-1z0z1c4/direnv-2.9.0/rc.go:131 +0x109 fp=0xc82004bba8 sp=0xc82004bb38
main.(*ExportContext).resetEnv(0xc82004bcd0)
	/private/tmp/direnv-20160719-50748-1z0z1c4/direnv-2.9.0/cmd_export.go:88 +0x16e fp=0xc82004bbe0 sp=0xc82004bba8
main.exportCommand(0xc82000a5d0, 0xc82000e8e0, 0x2, 0x2, 0x4618658, 0xc82000fa20)
	/private/tmp/direnv-20160719-50748-1z0z1c4/direnv-2.9.0/cmd_export.go:159 +0x567 fp=0xc82004bd08 sp=0xc82004bbe0
main.CommandsDispatch(0xc82000a5d0, 0xc82000a270, 0x3, 0x3, 0x0, 0x0)
	/private/tmp/direnv-20160719-50748-1z0z1c4/direnv-2.9.0/commands.go:90 +0x3d3 fp=0xc82004beb0 sp=0xc82004bd08
main.main()
	/private/tmp/direnv-20160719-50748-1z0z1c4/direnv-2.9.0/main.go:16 +0x98 fp=0xc82004bf50 sp=0xc82004beb0
runtime.main()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc82004bfa0 sp=0xc82004bf50
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82004bfa8 sp=0xc82004bfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [select]:
main.CommandsDispatch.func1(0xc82005eee0, 0xc82000a270, 0x3, 0x3)
	/private/tmp/direnv-20160719-50748-1z0z1c4/direnv-2.9.0/commands.go:81 +0x1f0
created by main.CommandsDispatch
	/private/tmp/direnv-20160719-50748-1z0z1c4/direnv-2.9.0/commands.go:87 +0x392
```

**Comment by zimbatm** [comment]
That's very weird. It's probably a go runtime issue since I'm not using any C extension.

Maybe you could try compiling with go 1.7.1 to see if it solves the issue.

**Comment by robdox** [comment]
I'm having this same issue, was a fix ever found?

**Comment by zimbatm** [comment]
Closing, can't repro
