### ISSUE TITLE
direnv does not run before everything

### ISSUE THREAD

**Issue by rolandjitsu** [direnv/direnv#300]
I'm experiencing some issues with direnv where it loads what I export in the shell to slow and breaks other tools:
```text
Error: Failed to replace env in config: ${NPM_TOKEN}
    at /Users/rolandjitsu/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/config/core.js:418:13
    at String.replace (<anonymous>)
    at envReplace (/Users/rolandjitsu/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/config/core.js:414:12)
    at parseField (/Users/rolandjitsu/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/config/core.js:392:7)
    at /Users/rolandjitsu/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/config/core.js:335:17
    at Array.forEach (<anonymous>)
    at Conf.add (/Users/rolandjitsu/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/config/core.js:334:23)
    at ConfigChain.addString (/Users/rolandjitsu/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (/Users/rolandjitsu/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/config/core.js:322:10)
    at /Users/rolandjitsu/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
/Users/rolandjitsu/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/npm.js:52
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/Users/rolandjitsu/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/npm.js:52:13)
    at process.errorHandler (/Users/rolandjitsu/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/utils/error-handler.js:213:18)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:373:26)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v8.6.0 --silent` to unset it.
warning package.json: No license field
error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
direnv: loading .envrc
direnv: export +ANDROID_KEYSTORE_PASSWORD +NPM_TOKEN +NPM_USER ~PATH
```

This happens because I use `nvm` to set the node version. And it seems that when it loads, it also tries to read the config from `.npmrc`:
```text
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
email=${NPM_USER}
always-auth=true
```

But direnv runs after all that, and I export `NPM_TOKEN` and `NPM_USER` from `.envrc`.

Is there a way to avoid all this?

**Comment by zimbatm** [comment]
did you try to change the loading order in your .bashrc or equivalent? otherwise a bit of cooperation is required between both tools. Look at the `layout node` in the direnv stdlib, it might be doing what you want (not sure).

**Comment by zimbatm** [comment]
Err I mean `use node`. See https://github.com/direnv/direnv/blob/master/stdlib.sh#L499-L514 for usage.

**Comment by rolandjitsu** [comment]
@zimbatm I did try to change the order, but that did not help much. I see, so direnv also tries to load a node binary? Or did I misinterpret that?

What do you suggest in this case?

**Comment by zimbatm** [comment]
you have two choices:

1. either figure out why the ordering is not working. If using bash, have a look at `echo $PROMPT_COMMAND` and follow from there
2. it's possible to replace nvm with direnv, at least the version switching part. it means removing the nvm hook that is installed in the .bashrc or equivalent to avoid interference. The .envrc would then be changed to something like that:
```sh
export NPM_USER=youruser
export NPM_TOKEN=yourtoken
# this comes from the direnv stdlib.sh file and looks for the node version using the .nvmrc file
use node
```

**Comment by rolandjitsu** [comment]
I will close this as it's mostly about how the user sets up their env. Thanks for the help @zimbatm
