### ISSUE TITLE
pyenv virtualenv crashes with error: failed to install pip via get-pip.py

### ISSUE THREAD

**Issue by kierun** [direnv/direnv#546]
**Describe the bug**

Sometimes, it appears random but happens all too often, when I `cd` into my project, I get a crash.

**To Reproduce**

Follow the set up on the wiki, enter, and leave the directory till crash occurs.,

**Expected behavior**

No crash.

**Environment**
 - OS: CentOS 7/
 - Shell: zsh
 - Direnv version: 2.20.1

**Additional context**
```
direnv: loading .envrc
Traceback (most recent call last):
  File "/home/usr/.pyenv/versions/3.7.4/bin/virtualenv", line 8, in <module>
    sys.exit(main())
  File "/home/usr/.pyenv/versions/3.7.4/lib/python3.7/site-packages/virtualenv.py", line 870, in main
    symlink=options.symlink,
  File "/home/usr/.pyenv/versions/3.7.4/lib/python3.7/site-packages/virtualenv.py", line 1162, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/home/usr/.pyenv/versions/3.7.4/lib/python3.7/site-packages/virtualenv.py", line 1532, in install_python
    shutil.copyfile(executable, py_executable)
  File "/home/usr/.pyenv/versions/3.7.4/lib/python3.7/shutil.py", line 121, in
copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 40] Too many levels of symbolic links: '/home/usr/.pyenv/versions/3.7.4/envs/umbrella-3.7.4/bin/python3.7'
Installing pip from https://bootstrap.pypa.io/get-pip.py...
pyenv: python: command not found

The `python' command exists in these Python versions:
  2.7.16
  2.7.5
  2.7.5/envs/neovim-2.7.5
  3.7.4
  3.7.4/envs/neovim-3.7.4
  neovim-2.7.5
  neovim-3.7.4

error: failed to install pip via get-pip.py
/home/usr/.direnvrc: line 47: /home/usr/.pyenv/versions/umbrella-3.7.4/bin/activate: No such file or directory
```

**Comment by zimbatm** [comment]
It would be helpful if you could also share the content of your ~/.direnvrc and .envrc.

At a glance it looks like the issue is coming from pyenv and not direnv.

**Comment by kierun** [comment]
Yes, I think you are right. I messed with things a little and the problem seems to have gone away. Apologies, probably some weird interaction with my set up.

**Comment by zimbatm** [comment]
no problem!
