### ISSUE TITLE
internal ‘direnv dotenv’ command can segfault

### ISSUE THREAD

**Issue by wbolster** [direnv/direnv#799]
**Describe the bug**

The (internal) ‘direnv dotenv’ can segfault when an invalid ‘shell’ argument is passed. The `dotenv` and `dotenv_if_exists` from the `direnv stdlib` always pass a hardcoded value `bash`, like so:

```
  eval "$("$direnv" dotenv bash "$@")"
```

…which results in something like this:

```
$ echo 'FOO=bar' >> some-dotenv-file
$ direnv dotenv bash some-dotenv-file
export FOO=$'bar';
```

But if the hardcoded ‘bash’ is replaced by something unrecognized, a panic happens; see below:

**To Reproduce**

``` shell
$ direnv dotenv foo /dev/null 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7203d9]

goroutine 1 [running]:
main.Env.ToShell(0xc00007cfc0, 0x0, 0x0, 0x0, 0x0)
	/home/zimbatm/go/src/github.com/direnv/direnv/env.go:93 +0x179
main.cmdDotEnvAction(0xc00007cf60, 0xc00007cf90, 0x3, 0x3, 0xc00007cf90, 0x2)
	/home/zimbatm/go/src/github.com/direnv/direnv/cmd_dotenv.go:52 +0x135
main.actionSimple.Call(0x7e95d0, 0xc00007cf60, 0xc00007cf90, 0x3, 0x3, 0x0, 0x1, 0x3)
	/home/zimbatm/go/src/github.com/direnv/direnv/commands.go:12 +0x4e
main.CommandsDispatch(0xc00007cf60, 0xc0000100c0, 0x4, 0x4, 0xc000057f78, 0x4062e5)
	/home/zimbatm/go/src/github.com/direnv/direnv/commands.go:125 +0x31b
main.main()
	/home/zimbatm/go/src/github.com/direnv/direnv/main.go:20 +0x9d
```

**Expected behavior**
An (internal) error happens, and a message is shown. Not a segfault. :)

**Environment**

```
$ direnv version
2.28.0

$ echo $SHELL
/bin/bash

$ $SHELL --version | head -n1
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
```

**Comment by zimbatm** [comment]
Thanks for the report!

If somebody wants to tackle this, the `DetectShell` function should be changed to return (Shell, error). That way the consumer is forced to handle that case.
