### ISSUE TITLE
direnv fetchurl segfaults

### ISSUE THREAD

**Issue by eval** [direnv/direnv#854]
**Describe the bug**
When doing `direnv fetchurl <some-url>` I get 
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff203f4c9e]
...
```

**To Reproduce**
```bash
# with $PWD not containing a .envrc
# and ~/.config/direnv being empty
$ direnv fetchurl https://gist.githubusercontent.com/eval/3a08a7a36fcbc654ce4e51d4b6714172/raw/72bf1d4455cebb7594c03ba935e60bb273942efd/env_vars_required
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff203f4c9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff203f4c9e
stack: frame={sp:0x7ffeefbff328, fp:0x7ffeefbff378} stack=[0x7ffeefb803c8,0x7ffeefbff430)
0x00007ffeefbff228:  0x01007ffeefbff248  0x0000000000000004 
0x00007ffeefbff238:  0x000000000000001f  0x00007fff203f4c9e 
0x00007ffeefbff248:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbff258:  0x0000000004035b51 <runtime.throw+0x0000000000000071>  0x00007ffeefbff2f8 
0x00007ffeefbff268:  0x0000000004368016  0x00007ffeefbff2b0 
0x00007ffeefbff278:  0x0000000004035e08 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000046072c0 
0x00007ffeefbff288:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbff298:  0x00007ffeefbff2f8  0x0000000004035b51 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff2a8:  0x00000000046072c0  0x00007ffeefbff2e8 
0x00007ffeefbff2b8:  0x0000000004035d90 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff2c8 
0x00007ffeefbff2c8:  0x0000000004035dc0 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000046072c0 
0x00007ffeefbff2d8:  0x0000000004035b51 <runtime.throw+0x0000000000000071>  0x00007ffeefbff2f8 
0x00007ffeefbff2e8:  0x00007ffeefbff318  0x0000000004035b51 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff2f8:  0x00007ffeefbff300  0x0000000004035b80 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbff308:  0x000000000436d67a  0x000000000000002a 
0x00007ffeefbff318:  0x00007ffeefbff368  0x000000000404b776 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbff328: <0x000000000436d67a  0x00000000046072c0 
0x00007ffeefbff338:  0x00007ffeefbff3a8  0x0000000000000000 
0x00007ffeefbff348:  0x00000000046076a0  0xffffffffffffffff 
0x00007ffeefbff358:  0x000000c0000b5ba0  0x00007fff203a67c6 
0x00007ffeefbff368:  0x00007ffeefbff3b0 !0x00007fff203f4c9e 
0x00007ffeefbff378: >0x00007ffeefbff3b0  0x00000000045b0000 
0x00007ffeefbff388:  0x00000000000003de  0x000000000427b185 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffeefbff398:  0x0000000004067f9f <runtime.syscall+0x000000000000001f>  0x000000c0000b59f0 
0x00007ffeefbff3a8:  0x000000000406790c <runtime.nanotime_trampoline+0x000000000000000c>  0x000000c0000b59c0 
0x00007ffeefbff3b8:  0x0000000004065e10 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffeefbff3c8:  0x0000000004001c00  0x1c00000000001018 
0x00007ffeefbff3d8:  0x0000000000000010  0x000000000463b038 
0x00007ffeefbff3e8:  0x0000000000000668  0x000000c0000001a0 
0x00007ffeefbff3f8:  0x0000000004063f29 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbff408:  0x00000000043d59e8  0x00000000046072c0 
0x00007ffeefbff418:  0x00007ffeefbff460  0x0000000004063e25 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbff428:  0x0000000004063ddd <runtime.rt0_go+0x000000000000013d> 
runtime.throw({0x436d67a, 0x46072c0})
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff203f4c9e
stack: frame={sp:0x7ffeefbff328, fp:0x7ffeefbff378} stack=[0x7ffeefb803c8,0x7ffeefbff430)
0x00007ffeefbff228:  0x01007ffeefbff248  0x0000000000000004 
0x00007ffeefbff238:  0x000000000000001f  0x00007fff203f4c9e 
0x00007ffeefbff248:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbff258:  0x0000000004035b51 <runtime.throw+0x0000000000000071>  0x00007ffeefbff2f8 
0x00007ffeefbff268:  0x0000000004368016  0x00007ffeefbff2b0 
0x00007ffeefbff278:  0x0000000004035e08 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000046072c0 
0x00007ffeefbff288:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbff298:  0x00007ffeefbff2f8  0x0000000004035b51 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff2a8:  0x00000000046072c0  0x00007ffeefbff2e8 
0x00007ffeefbff2b8:  0x0000000004035d90 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff2c8 
0x00007ffeefbff2c8:  0x0000000004035dc0 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000046072c0 
0x00007ffeefbff2d8:  0x0000000004035b51 <runtime.throw+0x0000000000000071>  0x00007ffeefbff2f8 
0x00007ffeefbff2e8:  0x00007ffeefbff318  0x0000000004035b51 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff2f8:  0x00007ffeefbff300  0x0000000004035b80 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbff308:  0x000000000436d67a  0x000000000000002a 
0x00007ffeefbff318:  0x00007ffeefbff368  0x000000000404b776 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbff328: <0x000000000436d67a  0x00000000046072c0 
0x00007ffeefbff338:  0x00007ffeefbff3a8  0x0000000000000000 
0x00007ffeefbff348:  0x00000000046076a0  0xffffffffffffffff 
0x00007ffeefbff358:  0x000000c0000b5ba0  0x00007fff203a67c6 
0x00007ffeefbff368:  0x00007ffeefbff3b0 !0x00007fff203f4c9e 
0x00007ffeefbff378: >0x00007ffeefbff3b0  0x00000000045b0000 
0x00007ffeefbff388:  0x00000000000003de  0x000000000427b185 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffeefbff398:  0x0000000004067f9f <runtime.syscall+0x000000000000001f>  0x000000c0000b59f0 
0x00007ffeefbff3a8:  0x000000000406790c <runtime.nanotime_trampoline+0x000000000000000c>  0x000000c0000b59c0 
0x00007ffeefbff3b8:  0x0000000004065e10 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffeefbff3c8:  0x0000000004001c00  0x1c00000000001018 
0x00007ffeefbff3d8:  0x0000000000000010  0x000000000463b038 
0x00007ffeefbff3e8:  0x0000000000000668  0x000000c0000001a0 
0x00007ffeefbff3f8:  0x0000000004063f29 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbff408:  0x00000000043d59e8  0x00000000046072c0 
0x00007ffeefbff418:  0x00007ffeefbff460  0x0000000004063e25 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbff428:  0x0000000004063ddd <runtime.rt0_go+0x000000000000013d> 
runtime.sigpanic()
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall]:
syscall.syscall(0x427b180, 0x1, 0x40487413, 0xc0000b5a80)
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/sys_darwin.go:22 +0x3b fp=0xc0000b59f0 sp=0xc0000b59d0 pc=0x4062bbb
syscall.syscall(0x1, 0x1, 0xc0000bc300, 0x1d)
	<autogenerated>:1 +0x26 fp=0xc0000b5a38 sp=0xc0000b59f0 pc=0x4068766
golang.org/x/sys/unix.ioctl(0x0, 0x1d, 0xc0000bc300)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/zsyscall_darwin_amd64.go:746 +0x39 fp=0xc0000b5a68 sp=0xc0000b5a38 pc=0x427ae19
golang.org/x/sys/unix.IoctlGetTermios(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/ioctl.go:63
github.com/mattn/go-isatty.IsTerminal(0xc0000b5cd8)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/mattn/go-isatty@v0.0.12/isatty_bsd.go:10 +0x50 fp=0xc0000b5ad8 sp=0xc0000b5a68 pc=0x427b230
main.cmdFetchURL(0xc000092fc0, {0xc0000be8e0, 0x2, 0x10}, 0xc0000be8e0)
	/private/tmp/direnv-20211128-73453-1ukmg/direnv-2.29.0/cmd_fetchurl.go:35 +0x112 fp=0xc0000b5df8 sp=0xc0000b5ad8 pc=0x42cbc72
main.actionWithConfig.Call(0x43835d0, 0xc0000be8f0, {0xc0000be8e0, 0x2, 0x2}, 0x30)
	/private/tmp/direnv-20211128-73453-1ukmg/direnv-2.29.0/commands.go:26 +0x7f fp=0xc0000b5e38 sp=0xc0000b5df8 pc=0x42ce65f
main.CommandsDispatch(0x435dadc, {0xc000092180, 0x3, 0x3})
	/private/tmp/direnv-20211128-73453-1ukmg/direnv-2.29.0/commands.go:125 +0x359 fp=0xc0000b5f18 sp=0xc0000b5e38 pc=0x42cf0d9
main.main()
	/private/tmp/direnv-20211128-73453-1ukmg/direnv-2.29.0/main.go:20 +0x75 fp=0xc0000b5f80 sp=0xc0000b5f18 pc=0x42d35f5
runtime.main()
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/proc.go:255 +0x227 fp=0xc0000b5fe0 sp=0xc0000b5f80 pc=0x40381e7
runtime.goexit()
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000b5fe8 sp=0xc0000b5fe0 pc=0x4066101

```

**Expected behavior**
No segfault.

**Environment**
 - OS: macOS Big Sur
 - Shell: bash, 5.1.4(1)-release
 - Direnv version 2.29.0 (2.28.0 works as expected)

**Additional context**

```bash
$ direnv status
direnv exec path /usr/local/bin/direnv
DIRENV_CONFIG /Users/gert/.config/direnv
bash_path /usr/local/bin/bash
disable_stdin false
warn_timeout 5s
whitelist.prefix []
whitelist.exact map[]
No .envrc loaded
No .envrc found
```
```
﻿

**Comment by eval** [comment]
This seems fixed in 2.30.0
